version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=stock_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lalit-docker:/var/lib/postgresql/data
    ports:
      - 5431:5432
    networks:
      - backend

  web:
    build: .
    restart: always
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=stock_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - backend

networks:
  backend:
    driver: bridge
