version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=stock_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - /usr/local/pgsql/data:/usr/local/pgsql/data
    networks:
      - backend

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - backend

networks:
  backend:
    driver: bridge
